#!/bin/sh

# Tries to reconfigure and restart networking.

status=0

echo "Stopping network..."

if [ -f /etc/init.d/ifplugd ]; then
	/bin/systemctl --quiet stop ifplugd
fi

/bin/systemctl --quiet stop networking

/bin/systemctl --quiet restart set-rfkill || status=1

echo "Regenerating network configuration..."

/bin/systemctl --quiet restart generate-network-config || status=1
/bin/systemctl --quiet daemon-reload || status=1

if [ -f /etc/init.d/dhcpcd ]; then
	echo "Restarting dhcpcd..."
	/sbin/dhcpcd --quiet --release || status=1
	/bin/systemctl --quiet restart dhcpcd || status=1
fi

/bin/systemctl --quiet restart rsyslog || status=1

echo "Starting network..."
/bin/systemctl --quiet start networking || status=1

if [ -f /etc/init.d/ifplugd ]; then
	/bin/systemctl --quiet start ifplugd || status=1
fi

echo "Done. Wait a moment for networking changes to take effect"

exit $status
