#!/bin/sh

# Tries to reconfigure and restart networking.

status=0

echo "Stopping network..."

nmcli con down wireless

/bin/systemctl --quiet restart NetworkManager || status=1

nmcli con up wireless

/bin/systemctl --quiet restart rsyslog || status=1


echo "Done. Wait a moment for networking changes to take effect"

exit $status
