#!/bin/sh -e

# Horrible hack. The raspberrypi-kernel packaging sets
# INITRD=No which inhibits the usual initrd generation;
# but we do want to run it, so reset that setting and
# rerun the hook..

if [ "$INITRD" = 'No' ] && [ -x /etc/kernel/postinst.d/initramfs-tools ]
then
    unset INITRD
    /etc/kernel/postinst.d/initramfs-tools "$@"
fi
