#!/bin/sh -e

# If ENABLED=yes in /etc/default/rpi-bootconfig,
# regenerate /boot/config.txt

[ -x /usr/lib/piaware-support/rpi-bootconfig ] || exit 0
[ -f /etc/default/rpi-bootconfig ] || exit 0
. /etc/default/rpi-bootconfig
[ "$ENABLED" = "yes" ] || exit 0

/usr/lib/piaware-support/rpi-bootconfig update
