#!/bin/sh -e

# Updates the Pi's /boot/config.txt when an initramfs
# image is updated. Only enabled if ENABLED=yes in
# /etc/default/rpi-bootconfig

[ -x /usr/lib/piaware-support/rpi-bootconfig ] || exit 0
[ -f /etc/default/rpi-bootconfig ] || exit 0
. /etc/default/rpi-bootconfig
[ "$ENABLED" = "yes" ] || exit 0

/usr/lib/piaware-support/rpi-bootconfig initramfs "$@"
