#!/bin/sh -e

#!/bin/sh -e

# Record install/update of an initramfs so that
# rpi-bootconfig can later use it to regenerate the Pi's
# /boot/config.txt.

[ -x /usr/lib/piaware-support/rpi-bootconfig ] || exit 0

/usr/lib/piaware-support/rpi-bootconfig initramfs "$@"
