#!/bin/sh -e

# If ENABLED=yes in /etc/default/rpi-bootconfig,
# regenerate /boot/config.txt

[ -x /usr/lib/piaware-support/rpi-bootconfig ] || exit 0
[ -f /etc/default/rpi-bootconfig ] || exit 0
. /etc/default/rpi-bootconfig
[ "$ENABLED" = "yes" ] || exit 0

case "$DPKG_MAINTSCRIPT_PACKAGE" in
    linux-image-*|raspberrypi-kernel)
        # Currently processing a change to the kernel package.
        # Don't run yet, wait for the postinst/postrm hook
        echo "rpi-bootconfig: deferring update of /boot/config.txt" >&2
        ;;

    *)
        /usr/lib/piaware-support/rpi-bootconfig update
        ;;
esac
